### ISSUE TITLE
Is this related to gaming.gg?

### ISSUE THREAD

**Issue by skanda890** [DraganD-Ukr/GaminGg#1]
If yes, then I got an error while trying to access gaming.gg through Telnet. Here is the error: " curl :

curl:

Please enable cookies.
Sorry, you have been blocked
You are unable to access gamin.gg

Why have I been blocked?
This website is using a security service to protect itself from online attacks. The action you just performed triggered the security solution.
There are several actions that could trigger this block including submitting a certain word or phrase, a SQL command or malformed data.
What can I do to resolve this?
You can email the site owner to let them know you were blocked. Please include what you were doing when this page came up and the Cloudflare Ray
ID found at the bottom of this page.

Cloudflare Ray ID: 825ce7282a4a4162 • Your IP: Click to reveal 171.76.81.149 •  Performance & security by Cloudflare
(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.rem
ove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var
a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();    window._cf_translation = {};
At line:1 char:1
+ curl gamin.gg
+ ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand "

**Comment by skanda890** [comment]
If not, then can you tell me where to report this?

**Comment by DraganD-Ukr** [comment]
@skanda890 No, it's not related to this website. Sorry for late reply though

**Comment by skanda890** [comment]
> @skanda890 No, it's not related to this website. Sorry for late reply though 

Then how, to access it.

**Comment by DraganD-Ukr** [comment]
@skanda890 access what?

**Comment by skanda890** [comment]
> @skanda890 access what?

How to access the website.

**Comment by DraganD-Ukr** [comment]
@skanda890 if you mean my website, then it's not available. It was made a part of my study in university. And if you mean gamin.gg - this repo and me have nothing to do with it.

**Comment by skanda890** [comment]
Okay.
